project:
  type: website
  output-dir: docs

website:
  title: "Zuzanna Wasiluk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - economics.qmd
      - statistics.qmd 

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    page-layout: full

editor: visual